# Generated by Django 4.0.5 on 2022-06-27 06:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('dispensed_on_time', 'Dispensed on time'), ('dispensed_on_time_incomplete', 'Dispensed on time (incomplete)'), ('late_dispense', 'Late Dispense'), ('late_dispense_incomplete', 'Late Dispense (incomplete)'), ('missed', 'Missed'), ('dispensed_to_cup_session', 'Dispensed to cup (by session)'), ('dispensed_to_cup_drug', 'Dispensed to cup (by drug)'), ('dispensed_to_pillbox', 'Dispensed to pillbox'), ('incomplete_dispense', 'Incomplete Dispense')], max_length=50)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DispensedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_session', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='DispensedDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_text', models.CharField(max_length=80)),
                ('quantity_to_be_taken', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quantity_actually_taken', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dispense_status', models.CharField(choices=[('dispensed', 'Dispensed'), ('manual', 'Manual'), ('skipped', 'Skipped')], max_length=40)),
                ('dispensed_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_drug', to='events.dispensedsession')),
            ],
        ),
    ]
